### ISSUE TITLE
Broken example in README.md

### ISSUE THREAD

**Issue by loganpar** [folaoluwafemi/rich_text_editor_controller#12]
README.md reads:
```
dependencies:
  flutter:
    sdk: flutter
  rich_text_editor_flutter: 0.0.4
 ```
 instead of:
 ```
 dependencies:
  flutter:
    sdk: flutter
  rich_text_editor_controller: 0.0.4
 ```
 
 
 And:
 ```pub add rich_text_editor_flutter```
 Instead of:
 ```pub add rich_text_editor_controller```
